controller:
  installPlugins:
    - github:latest
    - job-dsl:latest
    - configuration-as-code:latest
    - kubernetes-cli:latest

  envFrom:
    - secretRef:
        name: github-credentials
    - secretRef:
        name: dockerhub-credentials

  JCasC:
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: "github"
                      username: "${GITHUB_USERNAME}"
                      password: "${GITHUB_TOKEN}"
                      description: "GitHub Credentials"
                  - usernamePassword:
                      scope: GLOBAL
                      id: "dockerhub-credentials"
                      username: "${DOCKERHUB_USERNAME}"
                      password: "${DOCKERHUB_PASSWORD}"
                      description: "DockerHub Credentials"
      jobs: |
        jobs:
          - script: >
              pipelineJob('deploy-app') {
                definition {
                    cpsScm {
                        scm {
                            git {
                                remote {
                                    url 'https://github.com/OriTzadok-hub/Elta-Assignment.git'
                                    credentials('github')
                                }
                                branches 'main'
                                scriptPath 'Jenkinsfile'
                            }
                        }
                    }
                }
              }

